### ISSUE TITLE
Void Linux build errors

### ISSUE THREAD

**Issue by Jakecheslekov** [mupen64plus/mupen64plus-ui-python#119]
Hey, I'm trying to get this to build on Void Linux but it would seem it doesn't recognize SDL2, I have ALL SDL2 packages installed already too. I got this to build via python. 

M64Py - A frontend for Mupen64Plus version 0.2.5

Traceback (most recent call last):
  File "/usr/bin/m64py", line 4, in <module>
    __import__('pkg_resources').run_script('m64py==0.2.5', 'm64py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/m64py-0.2.5-py2.7.egg/EGG-INFO/scripts/m64py", line 57, in <module>
    from m64py.frontend.mainwindow import MainWindow
  File "/home/kzn/Compiles/mupen64plus-ui-python/src/m64py/frontend/mainwindow.py", line 30, in <module>
    from m64py.frontend.worker import Worker
  File "/home/kzn/Compiles/mupen64plus-ui-python/src/m64py/frontend/worker.py", line 21, in <module>
    from sdl2 import SDL_EnableScreenSaver, SDL_DisableScreenSaver
ImportError: No module named sdl2

**Comment by gen2brain** [comment]
You don't have PySDL2 installed. https://pysdl2.readthedocs.io/en/rel_0_9_6/install.html

**Comment by Jakecheslekov** [comment]
I do have PySDL2 installed though... I definitely have it installed.

when I use the command in the arch linux PKGBUILD for m64py I get this error:

Traceback (most recent call last):
  File "/usr/bin/m64py", line 4, in <module>
    __import__('pkg_resources').run_script('m64py==0.2.5', 'm64py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/m64py' not found in metadata at '/usr/lib/python2.7/site-packages/m64py-0.2.5-py2.7.egg-info'

**Comment by Jakecheslekov** [comment]
there are two _ 's before and after import & init. 

init.py? Is it trying to do something with my init system? Void Linux uses Runit.

**Comment by gen2brain** [comment]
That init.py is not from m64py packages, and I doubt is in any way related to your init system. Anyway, do you have PySDL2 installed for python2 or python3? With what version are your trying to run m64py?
If it is installed this should just work:
```
$ python
Python 2.7.14 (default, Nov 15 2017, 06:12:42) 
[GCC 6.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdl2
>>> 

```

**Comment by Jakecheslekov** [comment]
>>> import sdl2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named sdl2

**Comment by Jakecheslekov** [comment]
[*] SDL-1.2.15_10             Simple Directmedia Layer
[*] SDL-devel-1.2.15_10       Simple Directmedia Layer - development files
[*] SDL2-2.0.7_2              Simple DirectMedia Layer (version 2)
[*] SDL2-devel-2.0.7_2        Simple DirectMedia Layer (version 2) - development files
[*] SDL2_gfx-1.0.3_1          SDL graphics drawing primitives
[*] SDL2_gfx-devel-1.0.3_1    SDL graphics drawing primitives - development files
[*] SDL2_image-2.0.2_1        Load images as SDL surfaces (SDL 2.x)
[*] SDL2_image-devel-2.0.2_1  Load images as SDL surfaces (SDL 2.x) - development files
[*] SDL2_mixer-2.0.2_1        Multi-channel audio mixer library (SDL 2.x)
[*] SDL2_mixer-devel-2.0.2_1  Multi-channel audio mixer library (SDL 2.x) - development files
[*] SDL2_net-2.0.1_2          SDL2 networking module
[*] SDL2_net-devel-2.0.1_2    SDL2 networking module - development files
[*] SDL2_ttf-2.0.14_1         Use TrueType fonts in your SDL 2.x applications
[*] SDL2_ttf-devel-2.0.14_1   Use TrueType fonts in your SDL 2.x applications - development files
[*] SDL_gfx-2.0.26_1          Graphics drawing primitives for SDL
[*] SDL_gfx-devel-2.0.26_1    Graphics drawing primitives for SDL - development files
[*] SDL_image-1.2.12_11       Load images as SDL surfaces
[*] SDL_image-devel-1.2.12_11 Load images as SDL surfaces - development files
[*] SDL_mixer-1.2.12_12       Multi-channel audio mixer library
[*] SDL_mixer-devel-1.2.12_12 Multi-channel audio mixer library - development files
[*] SDL_net-1.2.8_4           Small sample cross-platform networking library for SDL
[*] SDL_net-devel-1.2.8_4     Small sample cross-platform networking library for SDL - development files
[*] SDL_sound-1.0.3_5         A library to decode several popular sound file formats, such as .WAV and .MP3
[*] SDL_sound-devel-1.0.3_5   A library to decode several popular sound file formats, such as .WAV and .MP3 - development files
[*] SDL_ttf-2.0.11_5          Use TrueType fonts in your SDL applications
[*] SDL_ttf-devel-2.0.11_5    Use TrueType fonts in your SDL applications - development files

**Comment by Jakecheslekov** [comment]
`[*] SDL-1.2.15_10             Simple Directmedia Layer
[*] SDL-devel-1.2.15_10       Simple Directmedia Layer - development files
[*] SDL2-2.0.7_2              Simple DirectMedia Layer (version 2)
[*] SDL2-devel-2.0.7_2        Simple DirectMedia Layer (version 2) - development files
[*] SDL2_gfx-1.0.3_1          SDL graphics drawing primitives
[*] SDL2_gfx-devel-1.0.3_1    SDL graphics drawing primitives - development files
[*] SDL2_image-2.0.2_1        Load images as SDL surfaces (SDL 2.x)
[*] SDL2_image-devel-2.0.2_1  Load images as SDL surfaces (SDL 2.x) - development files
[*] SDL2_mixer-2.0.2_1        Multi-channel audio mixer library (SDL 2.x)
[*] SDL2_mixer-devel-2.0.2_1  Multi-channel audio mixer library (SDL 2.x) - development files
[*] SDL2_net-2.0.1_2          SDL2 networking module
[*] SDL2_net-devel-2.0.1_2    SDL2 networking module - development files
[*] SDL2_ttf-2.0.14_1         Use TrueType fonts in your SDL 2.x applications
[*] SDL2_ttf-devel-2.0.14_1   Use TrueType fonts in your SDL 2.x applications - development files
[*] SDL_gfx-2.0.26_1          Graphics drawing primitives for SDL
[*] SDL_gfx-devel-2.0.26_1    Graphics drawing primitives for SDL - development files
[*] SDL_image-1.2.12_11       Load images as SDL surfaces
[*] SDL_image-devel-1.2.12_11 Load images as SDL surfaces - development files
[*] SDL_mixer-1.2.12_12       Multi-channel audio mixer library
[*] SDL_mixer-devel-1.2.12_12 Multi-channel audio mixer library - development files
[*] SDL_net-1.2.8_4           Small sample cross-platform networking library for SDL
[*] SDL_net-devel-1.2.8_4     Small sample cross-platform networking library for SDL - development files
[*] SDL_sound-1.0.3_5         A library to decode several popular sound file formats, such as .WAV and .MP3
[*] SDL_sound-devel-1.0.3_5   A library to decode several popular sound file formats, such as .WAV and .MP3 - development files
[*] SDL_ttf-2.0.11_5          Use TrueType fonts in your SDL applications
[*] SDL_ttf-devel-2.0.11_5    Use TrueType fonts in your SDL applications - development files`

**Comment by Jakecheslekov** [comment]
I get almost the same error on Devuan ASCII too. Very strange... It tells me I don't have sdl2, but I do!

**Comment by Jakecheslekov** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/m64py", line 4, in <module>
    __import__('pkg_resources').run_script('m64py==0.2.5', 'm64py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/m64py-0.2.5-py2.7.egg/EGG-INFO/scripts/m64py", line 57, in <module>
    from m64py.frontend.mainwindow import MainWindow
  File "/usr/local/lib/python2.7/dist-packages/m64py-0.2.5-py2.7.egg/m64py/frontend/mainwindow.py", line 30, in <module>
    from m64py.frontend.worker import Worker
  File "/usr/local/lib/python2.7/dist-packages/m64py-0.2.5-py2.7.egg/m64py/frontend/worker.py", line 21, in <module>
    from sdl2 import SDL_EnableScreenSaver, SDL_DisableScreenSaver
ImportError: No module named sdl2

**Comment by gen2brain** [comment]
It is not strange, you have SDL2, but you don't have PySDL2 (Python bindings for SDL2) , there are many distros that don't package it.  Just download archive from here https://bitbucket.org/marcusva/py-sdl2/downloads/ , unpack somewhere and install with `python setup.py install`.
