### ISSUE TITLE
[SOLVED] How do I actually start the application (Fedora)?

### ISSUE THREAD

**Issue by Sbalian02** [mupen64plus/mupen64plus-ui-python#124]
Rookie question here, but I successfully installed mupen64plus-ui-python by running the following three commands on Fedora 27 :

cd ~/mupen64plus-ui-python-master/
python setup.py build
sudo python setup.py install

Now how do I actually start mupen64, which file should I execute? The ReadMe file gave the install instructions, but nothing about how to start. Thanks!

**Comment by gen2brain** [comment]
Hi, frontend is started with `m64py` , but you will probably have this issue https://github.com/mupen64plus/mupen64plus-ui-python/issues/91 .

**Comment by Sbalian02** [comment]
Thanks gen2brain,

`m64py` returned the following:

M64Py - A frontend for Mupen64Plus version 0.2.5

Traceback (most recent call last):
  File "/usr/bin/m64py", line 4, in <module>
    __import__('pkg_resources').run_script('m64py==0.2.5', 'm64py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/m64py-0.2.5-py2.7.egg/EGG-INFO/scripts/m64py", line 57, in <module>
    from m64py.frontend.mainwindow import MainWindow
  File "/home/sarkis/mupen64plus-ui-python-master/src/m64py/frontend/mainwindow.py", line 30, in <module>
    from m64py.frontend.worker import Worker
  File "/home/sarkis/mupen64plus-ui-python-master/src/m64py/frontend/worker.py", line 21, in <module>
    from sdl2 import SDL_EnableScreenSaver, SDL_DisableScreenSaver
ImportError: No module named sdl2

**Comment by Sbalian02** [comment]
Update:

Just downloaded and extracted mupen64plus-GLideN64-linux64.zip
Double-clicked mupen64plus and everything worked.
