### ISSUE TITLE
Can't start m64py

### ISSUE THREAD

**Issue by JakobDev** [mupen64plus/mupen64plus-ui-python#162]
When I try to start m64py, I get the following error:
```
jakob@PC:~/Programme/m64py-0.2.5/bin$ ./m64py 
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.5

Traceback (most recent call last):
  File "./m64py", line 57, in <module>
    from m64py.frontend.mainwindow import MainWindow
  File "/home/jakob/Programme/m64py-0.2.5/src/m64py/frontend/mainwindow.py", line 26, in <module>
    from m64py.frontend.dialogs import *
  File "/home/jakob/Programme/m64py-0.2.5/src/m64py/frontend/dialogs.py", line 22, in <module>
    from m64py.ui.about_ui import Ui_AboutDialog
ModuleNotFoundError: No module named 'm64py.ui.about_ui'
jakob@PC:~/Programme/m64py-0.2.5/bin$ 
```

**Comment by gen2brain** [comment]
Looks like you didn't `setup.py build` before the start, you have instructions in readme.
