### ISSUE TITLE
Crash upon trying to configure input

### ISSUE THREAD

**Issue by cobbleking** [mupen64plus/mupen64plus-ui-python#188]
This is on Fedora 34, using default input plugin.

First time I try clicking on the 'configure' button next to the input plugin, console shows this output:

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: video extension enabled
Traceback (most recent call last):
  File "/home/wren/.local/lib/python3.9/site-packages/m64py-0.2.5-py3.9.egg/m64py/frontend/input.py", line 85, in show_dialog
    self.set_items()
  File "/home/wren/.local/lib/python3.9/site-packages/m64py-0.2.5-py3.9.egg/m64py/frontend/input.py", line 93, in set_items
    self.set_opts(), self.set_keys()
  File "/home/wren/.local/lib/python3.9/site-packages/m64py-0.2.5-py3.9.egg/m64py/frontend/input.py", line 241, in set_opts
    spin1.setValue(int(paramX))
ValueError: invalid literal for int() with base 10: '"4096'

Second time, it shows this:

Unhandled Python exception
zsh: IOT instruction (core dumped)  m64py

Input plugin itself works fine, it's only the GUI config that won't work.

**Comment by gen2brain** [comment]
Please try with the new release, this should be fixed.
