### ISSUE TITLE
Something wrong with compile

### ISSUE THREAD

**Issue by vitacell** [mupen64plus/mupen64plus-ui-python#70]
vita@GNUvita ~/Escritorio/mupen64plus-ui-python-master $ python setup.py installrunning install
running build
running build_qt
Traceback (most recent call last):
  File "setup.py", line 380, in <module>
    ("share/applications", ["xdg/m64py.desktop"]),
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 344, in run
    self.run_command("build_qt")
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 63, in run
    self.compile_ui(join(dirpath, filename))
  File "setup.py", line 34, in compile_ui
    from PyQt5 import uic
ImportError: No module named PyQt5

---

vita@GNUvita ~/Escritorio/mupen64plus-ui-python-master $ python setup.py build_qt
running build_qt
Traceback (most recent call last):
  File "setup.py", line 380, in <module>
    ("share/applications", ["xdg/m64py.desktop"]),
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 63, in run
    self.compile_ui(join(dirpath, filename))
  File "setup.py", line 34, in compile_ui
    from PyQt5 import uic
ImportError: No module named PyQt5

---

I have every package needed, including -dev packages.

**Comment by rafaelmessias** [comment]
Not sure what distribution you're running, but on Ubuntu 15.10 I had to install the following packages:
**pyqt5-dev**, **pyqt5-dev-tools** and **python-pyqt5.qtopengl**.
