### ISSUE TITLE
Issues with mupen64plus library

### ISSUE THREAD

**Issue by CalebQ42** [mupen64plus/mupen64plus-ui-python#75]
I'm currently running Fedora 23 and can't seem to get m64py to install properly. I've install from source (the RPM file from m64py.sourceforge.net simply showed a black box for a second before it crashed) and it throws up the first error below about the library not found, but the gui does load with a small window that says "Mupen64Plus library not found" which I click through and select the libmupen64plus.so.2 file for the Library File field and it throws up the final error and the entire thing crashes
I've tried installing mupen64plus from source and from a repo I found and neither makes it work. My mupen64plus instillation is found at /usr/local/share/mupen64plus and I sym-linked the libmupen64plus.so.2 to /usr/local/lib/mupen64plus (I saw it was in a list of accepted locations)

```
Frontend: ERROR: 'Mupen64Plus Core' library not found.
Traceback (most recent call last):
  File "/home/belac/Downloads/mupen64plus-ui-python-master/src/m64py/core/core.py", line 94, in core_load
    raise Exception("'%s' library not found." % self.core_name)
Exception: 'Mupen64Plus Core' library not found.
Frontend: INFO: attached to library 'Mupen64Plus Core' version 1.99.5
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: video extension enabled
Traceback (most recent call last):
  File "/home/belac/Downloads/mupen64plus-ui-python-master/src/m64py/frontend/settings.py", line 111, in <lambda>
    (self.pathLibrary, self.groupLibrary, False)))
  File "/home/belac/Downloads/mupen64plus-ui-python-master/src/m64py/frontend/settings.py", line 153, in browse_dialog
    self.set_core()
  File "/home/belac/Downloads/mupen64plus-ui-python-master/src/m64py/frontend/settings.py", line 283, in set_core
    self.core.config.get_parameter_help("DelaySI").decode())
AttributeError: 'NoneType' object has no attribute 'decode'
Aborted (core dumped)
```

**Comment by gen2brain** [comment]
You need to update mupen64plus, that is old version, version 2.5 is the latest.

**Comment by CalebQ42** [comment]
I updated to the latest mupen64plus but I'm still getting the error
```
Frontend: ERROR: 'Mupen64Plus Core' library not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/m64py/core/core.py", line 94, in core_load
    raise Exception("'%s' library not found." % self.core_name)
Exception: 'Mupen64Plus Core' library not found.
Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.0
Frontend: INFO: includes support for Dynamic Recompiler.
Frontend: INFO: video extension enabled
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/m64py/frontend/settings.py", line 111, in <lambda>
    (self.pathLibrary, self.groupLibrary, False)))
  File "/usr/lib/python2.7/site-packages/m64py/frontend/settings.py", line 154, in browse_dialog
    self.set_video()
  File "/usr/lib/python2.7/site-packages/m64py/frontend/settings.py", line 247, in set_video
    self.core.config.get_parameter_help("VerticalSync").decode())
AttributeError: 'NoneType' object has no attribute 'decode'
Aborted (core dumped)
```

**Comment by gen2brain** [comment]
Try to remove mupen64plus.cfg from your home, it is probably from old version.

**Comment by CalebQ42** [comment]
didn't work, still getting the same error

**Comment by gen2brain** [comment]
Try with new release, and file a new issue if there is a need. Thanks.

**Comment by marco-lilek** [comment]
Just built from source, happened whenever I try to use any of entries under "Settings"

```
20:30:03 mllilek mllilek-debian ~ $ ~/.local/bin/m64py 
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.5

Frontend: INFO: attached to library 'Mupen64Plus Core' version 2.5.9
Frontend: INFO: includes support for Dynamic Recompiler.
Core: Couldn't open configuration file '/home/mllilek/.config/mupen64plus/mupen64plus.cfg'.  Using defaults.
Core: No version number in 'Core' config section. Setting defaults.
Core: No version number in 'CoreEvents' config section. Setting defaults.
Core: Using full mem base
Frontend: DEBUG: override_vidext()
Frontend: WARNING: INPUT_INVALID: An input function parameter is logically invalid
Traceback (most recent call last):
  File "/home/mllilek/.local/lib/python2.7/site-packages/m64py-0.2.5-py2.7.egg/m64py/frontend/settings.py", line 51, in showEvent
    self.set_config()
  File "/home/mllilek/.local/lib/python2.7/site-packages/m64py-0.2.5-py2.7.egg/m64py/frontend/settings.py", line 99, in set_config
    self.set_video()
  File "/home/mllilek/.local/lib/python2.7/site-packages/m64py-0.2.5-py2.7.egg/m64py/frontend/settings.py", line 247, in set_video
    self.core.config.get_parameter_help("VerticalSync").decode())
AttributeError: 'NoneType' object has no attribute 'decode'
Aborted

```
