### ISSUE TITLE
[Linux] Debian Stable Jessie Fail to Start

### ISSUE THREAD

**Issue by inukaze** [mupen64plus/mupen64plus-ui-python#83]
git clone https://github.com/mupen64plus/mupen64plus-ui-python
cd mupen64plus-ui-python
python setup.py build_qt
./m64py

```
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.3

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
Frontend: INFO: No OpenGL_accelerate module loaded: No module named OpenGL_accelerate
Frontend: INFO: Unable to load registered array format handler numeric:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/numeric.py", line 15, in <module>
    raise ImportError( """No Numeric module present: %s"""%(err))
ImportError: No Numeric module present: No module named Numeric

Frontend: INFO: Unable to load registered array format handler vbo:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name GL

Frontend: INFO: Unable to load registered array format handler vbooffset:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python2.7/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/vbo.py", line 33, in <module>
    from OpenGL import GL
ImportError: cannot import name GL

Frontend: ERROR: None: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
Traceback (most recent call last):
  File "/media/Compartido/Linux/src/Videojuegos/Emuladores/mupen64plus/mupen64plus-ui-python/src/m64py/core/core.py", line 90, in core_load
    self.m64p = load(path)
  File "/media/Compartido/Linux/src/Videojuegos/Emuladores/mupen64plus/mupen64plus-ui-python/src/m64py/loader.py", line 87, in load
    raise ImportError(e)
ImportError: None: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
```

The graphics in the menu stucks. and when i click none button make something.

**Comment by gen2brain** [comment]
Try with new release.

**Comment by reggna** [comment]
I had the same exceptions running 0.2.4 in Ubuntu 14.4.  I fixed the errors by updating the OpenGL package:
`sudo pip3 install PyOpenGL --upgrade`

The problem I'm having now is that the menu doesn't show up at all.  There's no errors, no exception, no nothing, not even when running in verbose mode.  Just the splash screen that never goes away.

**Comment by gen2brain** [comment]
@reggna Are you using standard DE in Ubuntu and do you have another session with some other DE to try? As I understand, they have a lot of Qt patches for OS X like menus. Just tried in latest Ubuntu, in VM and it works fine.

@inukaze You cannot force version, they are different libraries. Last version with Qt4 was 0.2.2.

**Comment by inukaze** [comment]
@gen2brain : which are the commands for use that version downloading from github ? for example, i remember i made something like that when i download GzDoom and i need the version 1.8.6. 

That is explained on their wiki -> https://zdoom.org/wiki/Compile_GZDoom_on_Linux#Make_gzdoom_build_directory , when you search 1.8.6 

should use :
`git checkout --detach refs/tags/g1.8.6`

for get version 1.8.6, something similar can work with your github ???
i'll go try the follow : 

```
git clone https://github.com/mupen64plus/mupen64plus-ui-python
cd mupen64plus-ui-python
git checkout --detach refs/tags/0.2.2
python setup.py build_qt
```

Its working :D 

```
$ ./m64py
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.2

Frontend: INFO: ScreenSaver not available: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
Frontend: ERROR: None: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
Traceback (most recent call last):
  File "/home/inukaze/mupen64plus-ui-python/src/m64py/core/core.py", line 90, in core_load
    self.m64p = load(path)
  File "/home/inukaze/mupen64plus-ui-python/src/m64py/loader.py", line 87, in load
    raise ImportError(e)
ImportError: None: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
Traceback (most recent call last):
  File "/home/inukaze/mupen64plus-ui-python/src/m64py/frontend/settings.py", line 49, in showEvent
    self.set_config()
  File "/home/inukaze/mupen64plus-ui-python/src/m64py/frontend/settings.py", line 94, in set_config
    if self.core.get_handle():
AttributeError: 'NoneType' object has no attribute 'get_handle'
Traceback (most recent call last):
  File "/home/inukaze/mupen64plus-ui-python/src/m64py/frontend/settings.py", line 52, in closeEvent
    self.save_config()
  File "/home/inukaze/mupen64plus-ui-python/src/m64py/frontend/settings.py", line 87, in save_config
    if self.core.get_handle():
AttributeError: 'NoneType' object has no attribute 'get_handle'
```

well i just must fix the paths xD

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
