### ISSUE TITLE
MacOS: ImportError: dlopen(None, 10): image not found

### ISSUE THREAD

**Issue by SeanHayes** [mupen64plus/mupen64plus-ui-python#94]
```
$ ./m64py 
 __  __                         __   _  _   ____  _            
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___  
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __| 
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \ 
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/ 
             |_|                                               

M64Py - A frontend for Mupen64Plus version 0.2.4

2017-02-10 19:11:01.975 defaults[42382:1409855] 
The domain/default pair of (com.apple.screensaver, idleTime) does not exist
Frontend: ERROR: dlopen(None, 10): image not found
Traceback (most recent call last):
  File "/Users/sean/Downloads/mupen64plus-ui-python-master/src/m64py/core/core.py", line 88, in core_load
    self.m64p = load(path)
  File "/Users/sean/Downloads/mupen64plus-ui-python-master/src/m64py/loader.py", line 87, in load
    raise ImportError(e)
ImportError: dlopen(None, 10): image not found
```

The UI doesn't respond to any clicks. I tried setting PYSDL2_DLL_PATH to a few different files from `/usr/local/Cellar/sdl2/2.0.5/lib/` but none worked.

`export PYSDL2_DLL_PATH=/usr/local/Cellar/sdl2/2.0.5/lib/libSDL2.dylib`

I'm on MacOS 10.12.3.

**Comment by gen2brain** [comment]
PYSDL2_DLL_PATH is not relevant there. libSDL2.dylib (symlink) should be in /usr/local/lib , if it is not there try to link it with brew.

**Comment by gen2brain** [comment]
v0.2.5 is released, try with the latest version, I will close this one. Feel free to open a new issue if it is not resolved.
