### ISSUE TITLE
PySDL2 for Fedora

### ISSUE THREAD

**Issue by karl6994** [mupen64plus/mupen64plus-ui-python#97]
I've compiled & installed PySDL2 0.9.5 & M64py still responds as if I haven't installed it, running Fedora 25, 32-bit. Mupen64plus works fine but M64py does not want to install, just lists the PySDL2 dependency as missing.

**Comment by gen2brain** [comment]
How did you install PySDL2 ? Are you trying to start with python3 maybe but you installed it for python2?

**Comment by karl6994** [comment]
I followed this guide on how to install PySDL2
http://pysdl2.readthedocs.io/en/rel_0_9_4/install.html

It may be installed on Python2, I honestly do not know :| I never went out of my way to select Python2 instead of Python3..

**Comment by john-cheesman** [comment]
I'm having the same problem, I believe it was installed for Python 2.7 when I did it.

**Comment by john-cheesman** [comment]
I just installed it for Python 3.5 `sudo python3 setup.py install` and still getting the same error

**Comment by john-cheesman** [comment]
I also manually set the `PYTHONPATH` variable to the sdl2 directory in both cases

**Comment by gen2brain** [comment]
Can you import sdl2 in python console? If not, then issue is not related to m64py.
```
milann@thinkpad ~ $ python
Python 2.7.13 (default, Mar  6 2017, 14:04:23) 
[GCC 5.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdl2
>>> 
milann@thinkpad ~ $ python3
Python 3.4.6 (default, Mar  6 2017, 14:06:08) 
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdl2
>>>
```

**Comment by john-cheesman** [comment]
Yes, looks like it:

```
~/Downloads/PySDL2-0.9.5                                                       
▶ python
Python 2.7.12 (default, Sep 29 2016, 13:30:34) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdl2
>>> 

~/Downloads/PySDL2-0.9.5                                                       
▶ python3 
Python 3.5.2 (default, Oct 14 2016, 12:54:53) 
[GCC 6.2.1 20160916 (Red Hat 6.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sdl2
>>> 
```

**Comment by gen2brain** [comment]
And how do you start m64py after that? Error was not posted in issue.

**Comment by john-cheesman** [comment]
I'm just running the rpm, which opens in yum extender and starts installing. Then I get this:

![yum-extender-error](https://cloud.githubusercontent.com/assets/4326107/24299039/c7892adc-109f-11e7-8a16-47a8e9a28229.png)

**Comment by john-cheesman** [comment]
I've tried from the command line as well:
```
▶ rpm -i m64py-0.2.4-1.noarch.rpm 
error: Failed dependencies:
	PySDL2 is needed by m64py-0.2.4-1.noarch
```

**Comment by gen2brain** [comment]
Ok, I understand now, rpm is broken. It requires PySDL2 but fedora doesn't have package for that. I will build and upload new rpm when I find time.

**Comment by loganmc10** [comment]
Isn't the reason for this that PySDL2 wasn't installed via RPM? How is rpm supposed to know that PySDL2 is installed?

**Comment by john-cheesman** [comment]
http://rpmfind.net/linux/rpm2html/search.php?query=pythonegg(2)(pysdl2)

I tried this but it calls it python-sdl2 so I guess it won't match

**Comment by YalithKBK** [comment]
Hello, I am trying to run this on Mint using the .deb file. I followed the import steps above and they did not produce any errors. However, I get a similar error with the sdl2 dependency not satisfied.
![screenshot from 2017-07-01 10 20 01](https://user-images.githubusercontent.com/8658787/27762812-1f5d4c8a-5e47-11e7-9114-7ef7fc0e4f30.png)

**Comment by karl6994** [comment]
So is there a fix for this yet? Would like to get the GUI working for mupen. good emulator, only one I don't have a front-end for.

**Comment by karl6994** [comment]
I got as far as installing this:
https://github.com/mupen64plus/mupen64plus-ui-python
but this comes up now:
M64Py - A frontend for Mupen64Plus version 0.2.5

Traceback (most recent call last):
  File "/bin/m64py", line 4, in <module>
    __import__('pkg_resources').run_script('m64py==0.2.5', 'm64py')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 741, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1502, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/m64py-0.2.5-py2.7.egg/EGG-INFO/scripts/m64py", line 57, in <module>
    from m64py.frontend.mainwindow import MainWindow
  File "/home/kz/Compiles/mupen64plus-ui-python/src/m64py/frontend/mainwindow.py", line 26, in <module>
    from m64py.frontend.dialogs import *
  File "/home/kz/Compiles/mupen64plus-ui-python/src/m64py/frontend/dialogs.py", line 22, in <module>
    from m64py.ui.about_ui import Ui_AboutDialog
ImportError: No module named about_ui

**Comment by loganmc10** [comment]
@karl6994 I don't mean to try to steal any thunder here, but if you are in need of a GUI for mupen64plus you can try https://github.com/m64p/mupen64plus-gui. It uses Qt5 like this one, but it's written in C++ instead of Python.

**Comment by karl6994** [comment]
The package qt5-default doesn't exist on Fedora under that name so not really sure what to do with that...

**Comment by loganmc10** [comment]
On fedora you just need to install ```qt5-devel``` i believe. And the command might be ```qmake-qt5``` instead of ```qmake```

**Comment by kuboosoft** [comment]
I am working a rpm for mupen64plus-gui (fedora) and the result is successful, It will published in unitedrpms...

My results failed with mupen64plus-ui-python  https://github.com/mupen64plus/mupen64plus-ui-python/issues/91#issuecomment-274265403

**Comment by karl6994** [comment]
I found a working mupen64plus-qt frontend, www.github.com/dh4/mupen64plus-qt I believe is the weblink

**Comment by gen2brain** [comment]
@karl6994 That is just a launcher, you should also check https://github.com/m64p/mupen64plus-gui , a frontend written also in Qt and C++.

**Comment by gen2brain** [comment]
PySDL2 issue on Fedora is simple to fix, dbus issue apparently not.

**Comment by kuboosoft** [comment]
@gen2brain but what is the problem in dbus, maybe we can share a bundled dbus... because touch a official package isn't good idea.
